In [20]:
# Imports
import pandas as pd

# Inserting game_id column to identift games
df = pd.read_csv("nba_games.csv")
df['game_id'] = df.index
first_column = df.pop('game_id')
df.insert(0, 'game_id', first_column)

# Train set
train = df.sample(frac=0.7)

# Test set
test = df[~df.index.isin(train.index)]

# Solution set
solution = test
solution = solution[['game_id', 'target']]

# Dropping target column in test as participants are required to predict this
test.drop("target",axis=1,inplace=True)

# Creating usage column to separate data into public and private for the Kaggle leaderboards
solution = pd.read_csv("solutions.csv")
solution['Usage'] = ['Public']*3092
solution['Usage'][2000:] = ['Private']*1092

# Creating sandbox submission (simply initialized everything to 1)
sandbox = solution
sandbox.drop('Usage',axis=1,inplace=True)
sandbox['target'] = 1
sandbox.to_csv("sandbox.csv", index=False)

# Saving the files
train.to_csv("train.csv", index=False)
test.to_csv("test.csv", index=False)
solution.to_csv("solutions.csv", index=False)

,game_id,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,1,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
2,2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
3,3,240.0,40.0,79.0,0.506,13.0,27.0,0.481,12.0,18.0,...,32.2,203.0,120.0,HOU,85,1,2016,2015-10-28,True,0
4,4,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,...,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10303,10303,240.0,36.0,84.0,0.429,7.0,25.0,0.280,15.0,24.0,...,36.2,158.0,101.0,HOU,128,1,2024,2023-11-08,False,1
10304,10304,240.0,45.0,96.0,0.469,11.0,27.0,0.407,17.0,18.0,...,30.4,225.0,117.0,IND,134,1,2024,2023-11-08,False,1
10305,10305,240.0,36.0,91.0,0.396,8.0,36.0,0.222,13.0,13.0,...,36.2,138.0,105.0,BRK,100,1,2024,2023-11-08,False,0
10306,10306,240.0,49.0,99.0,0.495,11.0,36.0,0.306,18.0,27.0,...,38.2,161.0,129.0,DAL,116,1,2024,2023-11-08,True,0
10307,10307,240.0,46.0,87.0,0.529,9.0,27.0,0.333,23.0,26.0,...,31.5,157.0,126.0,IND,126,1,2024,2023-11-09,False,0